### ISSUE TITLE
Code-Signing: Profile and Certificate

### ISSUE THREAD

**Issue by alloy** [artsy/emission-nebula#4]
* I had to let Xcode download the profiles from ADC.
* I don’t have the associated certificate nor is it available in the [code-signing repo](https://github.com/artsy/mobile_code_signing), so it’s not possible to build using the configured provisioning profile.

**Comment by alloy** [comment]
I now see that [Circle is running `match`](https://circleci.com/gh/artsy/emission-nebula/6?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) and using [another repo](https://github.com/artsy/mobile_fastlane_match), why is that? And is the user supposed to build the archive themselves as outlined in the README or will Circle build the archive and upload it?

**Comment by orta** [comment]
https://github.com/artsy/artsy.github.io/pull/345

the mobile_code_signing repo is hard for apps that are rarely deployed, got it wrong loads

**Comment by alloy** [comment]
And apparently Circle doesn’t have the nvm scripts in the usual location… I’m kinda at a loss of how this should be working, can you give me some guidance?

**Comment by orta** [comment]
Yeah, deploying this has been a total nightmare. [I'll do it manually](https://github.com/artsy/emission-nebula#deploying-manually).

**Comment by alloy** [comment]
Thanks 🙏

**Comment by orta** [comment]
Closing this, there's less ambiguity about this repo (only runs on travis now)
